### ISSUE TITLE
TVMenuControl module isn't working with React Native Navigation.

### ISSUE THREAD

**Issue by cnblackxp** [react-native-tvos/react-native-tvos#69] opened 2020-05-24 20:15 UTC
So I have been working on a project using React Native Navigation and been seeing some problems with `TVMenuControl `Module for disabling and enabling (it's not working) I believe it's related to how React Native Navigation basically on every screen navigation sets that screen as the RootView.

I also noticed that the bridge is working fine but the issue might be with `NSNotificationCenter `it's not posting the notification.

React Native version: 0.62

## Steps To Reproduce

1. Use React Native Navigation
2. Navigate to a new screen
3. call `disableTVMenuKey `it doesn't work

**Comment by ali-sao** [comment] 2020-05-26 10:00
+1 to this

**Comment by mahdi-hamdan** [comment] 2020-05-26 10:49
**I have the same problem**  @dlowder-salesforce

**Comment by dlowder-salesforce** [comment] 2020-05-26 16:56
I'll have a look...  my first guess is that RNN is putting in its own gesture handler for the root view that is replacing the one used by react-native-tvos.

**Comment by dlowder-salesforce** [comment] 2020-05-31 02:36
Ok this is not a bug.  I built a tvOS version of Wix's react-native-crash-course project (which uses React Native Navigation).... you can find it at https://github.com/dlowder-salesforce/react-native-crash-course-tvos/tree/tvos-0.62.2 .

Several dependencies (react-native-navigation, react-native-blur, react-native-ui-lib) required fixes for tvOS compilation errors.  I forked the repos and made the required changes, as you'll see in the package.json for the above sample project.

Once I got everything working, I see that the project exhibits correct behavior, _without any need for TVMenuControl_.  This is because RNN is pushing real native views onto a UINavigationController stack, so the menu key works natively without any special gesture recognizer needed.  Details are discussed at https://stackoverflow.com/questions/32663814/override-apple-siri-remote-menu-button-default-behavior .

So I'm happy to report that you don't need TVMenuControl at all :)

**Comment by cnblackxp** [comment] 2020-05-31 07:33
thanks @dlowder-salesforce, but I just want to mention that my issue isn't related to the navigation not working. the enableTVMenuKey and disableTVMenuKey aren't working properly. I have use cases in the project where I don't want the default menuKey behaviour and others where I do and the postNotification calls aren't working on the same screen when called from react native side.
postNotification isn't responding well and I think it's related to the way react native navigation is using multithreading somehow to set root views. but I am not sure, what I am sure of is that postNotification using things like disableTVMenuKey and enableTVMenuKey isn't working well.

again thanks for the help. it's much appreciated.

**Comment by dlowder-salesforce** [comment] 2020-05-31 08:49
Thanks for explaining the actual issue that you're having.  I can reproduce this in the example project I created, and I'll reopen this and have a look.

**Comment by ali-sao** [comment] 2020-05-31 23:04
على راسي يا ختيار. لسه فيك نفس تشوف

**Comment by fasci** [comment] 2021-02-04 12:55
Even though I don't use RNN, for me this still seems to be an issue when using `createNativeStackNavigator` from `react-native-screens/native-stack`. I'm not quite sure if it is indeed related to the original issue mentioned here, but as react-native-screens also uses a native screen, it might be the same issue.

Whenever a screen is pushed, `TVMenuControl.enableTVMenuKey();` has no effect anymore, and the screen is immediately popped again when pressing the tvOS menu button. So my BackHandler listener is ignored. 
This is not an issue with the root screen of my navigation stack.

Any hint towards a solution would be much appreciated.

Tried this with:
react-native-tvos 0.63.4-0
react-navigation/stack 5.12.8
react-native-screens 2.17.1

**Comment by fasci** [comment] 2021-02-04 17:08
I can get this to work by listening to `RCTTVEnableMenuKeyNotification` and `RCTTVDisableMenuKeyNotification` in react-native-screen's `RNSScreenView` and then adding `RCTTVRemoteHandler's` `tvMenuKeyRecognizer` to this view.
This prevents the UINavigationViewController to handle the event before it could be handled by `RCTRootView`.
However, this is just a hack in react-native-screen, so if there are better ideas out there, please let me know.

**Comment by fasci** [comment] 2021-03-05 10:37
Just in case somebody else wants to use `createNativeStackNavigator`, I created a fork or `react-native-screens` to make `TVMenuControl.enableTVMenuKey();` work with it:
https://github.com/fasci/react-native-screens

**Comment by douglowder** [comment] 2021-09-10 23:34
@fasci I've picked up this bug again, will keep you updated.  Thanks for the `react-native-screens` contribution!

**Comment by douglowder** [comment] 2021-09-13 21:31
Ok I've got a working demo app at https://github.com/douglowder/rnn-starter, that has current RNN fully working on tvOS.  In digging through the issues, I find the following:

- RNN doesn't have to use `react-native-screens`, so a fix there will not work in all cases
- If I run this app in "three_tabs" mode, it uses a bottom bar nav which is implemented as a `UITabBar`.  In this case, even the other TV events (up, down, etc.) don't show up.
- Debugging the view hierarchy indicates that the place to hook into RNN is probably `RNNStackController`.

Continuing to investigate.

**Comment by douglowder** [comment] 2021-09-17 02:36
I've put together a fix for this.  It requires changes both here and in RNN (but RNN requires a lot of patches for tvOS anyway).  Creating a PR.

**Closed** 2021-09-18 18:19 UTC
Labels: Type: Bug, in progress

**Comment by douglowder** [comment] 2021-09-18 20:39
Fixed in release 0.64.2-4

**Comment by douglowder** [comment] 2021-09-19 20:46
@fasci see https://github.com/react-native-tvos/rnn-starter-tv/commit/6930e918b684d84288e1acea93aca530c9f72862 for the patches needed to make RNN work on TV.

**Comment by NickAVolpe** [comment] 2022-05-09 16:00
> Has anyone found a way to override the backHandler for tvOS with React navigation? enableTVMenuKey doesn't seem to work

I fixed my issue by referencing the sample code Sir Doug Lowder wrote [here](https://github.com/react-native-tvos/ReactNavigationTVDemo/blob/master/App.js#L16)

I think what fixed it for me was to remove the "Native" stack API and use the non-native API that React Navigation has. I'm not entirely positive on that though. I can post my dependency versions if you want to compare.

**Comment by RobertArissen** [comment] 2022-05-10 09:11
Removing native stack and replace it with non-native fixt it for me! Ty @NickAVolpe !
