### ISSUE TITLE
[TVOS NEW ARCH] Trap focus is not working

### ISSUE THREAD

**Issue by AtakanMavzer** [react-native-tvos/react-native-tvos#800] opened 2024-10-10 07:31 UTC
Hi,
Simple code below is not working properly. Cannot trap focus.

Version Tested: 0.74.3-0

``` <View style={{flexDirection: "column", height: "100%"}}>
            <TVFocusGuideView
                style={{width: 200, height: 100}}
                trapFocusDown={true}
                trapFocusUp={true}
                trapFocusLeft={true}
                trapFocusRight={true}>
                <AssetButton
                    ref={ref1}
                    title="Hello1"
                    onPress={() => {
                        console.log("ref1 focused");
                    }}
                />
            </TVFocusGuideView>
            <TVFocusGuideView
                style={{width: 200, height: 100}}
                trapFocusDown={true}
                trapFocusUp={true}
                trapFocusLeft={true}
                trapFocusRight={true}>
                <AssetButton
                    ref={ref3}
                    title="Hello3"
                    onPress={() => {
                        console.log("ref3 focused");
                    }}
                />
            </TVFocusGuideView>
        </View>```

**Comment by douglowder** [comment] 2024-10-10 09:09
Dupe of #769 ...

**Closed by douglowder** 2024-10-10 09:09 UTC
