### ISSUE TITLE
Cannot start stream of HLS video in tvOS after upgrade to version 0.73.0

### ISSUE THREAD

**Issue by mendoza** [react-native-tvos/react-native-tvos#662] opened 2024-02-13 23:41 UTC
### New Version

0.73

### Old Version

0.71

### Build Target(s)

tvOS simulator, androidTV simulator

### Output of `react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M3
  Memory: 137.59 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 3.1.4
    path: /opt/homebrew/opt/ruby@3.1/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.2-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.73.4 is now available (your project is running on v0.73.2-0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.4
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".

### Issue and Reproduction Steps

# Issue
Recently my team and I faced an issue with certain Apple devices, those Apple TV with direction keys, where focus wouldn't move with swipes unless you press a direction key first, after doing it would work as expected. We decided to upgrade from `react-native-tvos@0.71.0` we upgraded to `react-native-tvos@0.73.0`, everything worked as expected! Until we got into the streaming screens of the app.

When you start video stream with HLS video in `react-native-video@^5.2.1` in tvOS, the audio tool box show these logs and the video/stream doesn't start, although it does works in androidTV as expected.

```sh
[CoreFoundation] AddInstanceForFactory: No factory registered for id <CFUUID 0x600000290440> F8BB1C28-BAE8-11D6-9C31-00039315CD46
[AudioToolbox]                AQMEIO.cpp:198   timed out after 15.000s (0 0); suspension count=0 (IOSuspensions: )
[AudioToolbox]  MEDeviceStreamClient.cpp:467   AQME Default-InputOutput: client stopping after failed start: <CA_UISoundClientBase@0x108107980>; running count now 0
[AudioToolbox]      CA_UISoundClient.cpp:293   CA_UISoundClientBase::StartPlaying: AddRunningClient failed (status = -66681).
[AudioToolbox]        MEMixerChannel.cpp:1006  MEMixerChannel::EnableProcessor: failed to open processor type 0x705f6571
[AudioToolbox]        MEMixerChannel.cpp:1006  MEMixerChannel::EnableProcessor: failed to open processor type 0x705f6571
[AudioToolbox]                AQMEIO.cpp:198   timed out after 15.000s (0 0); suspension count=0 (IOSuspensions: )
[AudioToolbox]  MEDeviceStreamClient.cpp:467   AQME Default-InputOutput: client stopping after failed start: <AudioQueueObject@0x10a838e00; Unknown figplayer;
[14037]; play>; running count now 0
```

# Steps to reproduce
create app using the template and installing react-native-video
```sh
yarn create react-native-app TestApp --template https://github.com/react-native-tvos/react-native-template-typescript-tv/tree/tv-release-0.73.0 --template-path template

cd TestApp

yard add react-native-video
yard add --dev @types/react-native-video
```

### package.json
```json
{
  "name": "testapp",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "start": "expo start",
    "tvos": "expo run:ios --scheme testApp-tvOS --device \"Apple TV\"",
    "lint": "eslint .",
    "test": "jest"
  },
  "dependencies": {
    "expo": "^50.0.2",
    "react": "18.2.0",
    "react-native": "npm:react-native-tvos@^0.73.2-0",
    "react-native-video": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "^0.73.19",
    "@react-native/eslint-config": "^0.73.2",
    "@react-native/metro-config": "^0.73.3",
    "@react-native/typescript-config": "^0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-native-video": "^5.0.19",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```
### app.tsx
```tsx
import React, {useRef} from 'react';
import {StyleSheet} from 'react-native';
import Video from 'react-native-video';
import VideoRef from 'react-native-video';

function App(): React.JSX.Element {
  const videoRef = useRef<VideoRef>(null);

  return (
    <Video
      // Big Buck Bunny video adaptive HLS stream URL
      source={{uri: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'}}
      // Store reference
      ref={videoRef}
      resizeMode="cover"
      style={styles.backgroundVideo}
    />
  );
}

var styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    backgroundColor: 'gray',
  },
});

export default App;
```

### tvOS
<img width="1453" alt="Screenshot 2024-02-13 at 17 20 00" src="https://github.com/react-native-tvos/react-native-tvos/assets/30415552/e3ad7abc-3655-488f-a0ce-6ef5a7859ecc">

### androidTV
![image](https://github.com/react-native-tvos/react-native-tvos/assets/30415552/c97a7af2-59b0-45f0-8694-3c8cf3a0b120)

**Comment by douglowder** [comment] 2024-02-14 02:35
@mendoza thanks for the detailed bug report and the repro! We will take a look.

**Comment by douglowder** [comment] 2024-02-14 02:49
I just tested with the latest release (0.73.4-0) and do not reproduce the issue on a simulator. Here is a quick repro that spins up a new Expo TV app similar to yours. With this, the video plays as expected.

```
# Create new Expo app configured for TV
yarn create expo-app TestVideo -e with-tv
# Install dependencies
cd TestVideo
yarn add react-native-video
# Copy your App.tsx, replacing the default one from the template
#....
# Build and run on Apple TV
export EXPO_TV=1
npx expo prebuild --clean
yarn ios

**Comment by mendoza** [comment] 2024-02-14 03:00
Do you think the problem could on the template? We have been using the react native template, I didn't see anywhere how to generate a project like you just showed me with expo, that's interesting 👀.

**Comment by douglowder** [comment] 2024-02-14 03:10
Yes most likely I need to update the tvOS target in the template Xcode project.

We at Expo just released SDK 50, which includes [Expo SDK TV support](https://docs.expo.dev/guides/building-for-tv/) (which I am very excited about 😄 )

**Comment by mendoza** [comment] 2024-02-14 03:23
I'm sorry, update the target to what? Or update what from the target? 🤔 the tvOS development target? 🤔  it's at 12.4 right now, also I'm testing 73.4 right now

**Comment by mendoza** [comment] 2024-02-14 03:32
I just tested the `react-native-tvos@0.73.4-0` version on our final project, it showed basically the same and this new error showed
```sh
LOG  Error {"error": {"code": -66681, "domain": "CoreMediaErrorDomain", "localizedDescription": "The operation couldn’t be completed. (CoreMediaErrorDomain error -66681.)", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 3455}
```

**Comment by douglowder** [comment] 2024-02-14 03:43
Sorry I should have said the tvOS scheme, not the tvOS target.

It's definitely an issue with the tvOS scheme, because the iOS scheme is not having the issue.

**Comment by douglowder** [comment] 2024-02-14 03:53
Ok I'll spend some time seeing if I can redo the template and fix this issue. I still have no idea why it is occurring -- I don't see any obvious reason.

In the meantime, I'd love to get your feedback on the new Expo flow for creating a TV project, and whether that will work for you. Among other things, you would have the option of using `expo-av` for video and audio.

**Comment by mendoza** [comment] 2024-02-14 04:09
Thanks for your help!

I will check the expo workflow, try the react native video component and test the expo av in case. And come back with what I see!

**Comment by mendoza** [comment] 2024-02-15 00:12
Hi @douglowder sorry to add this question here, but seems like a right place to do it, I followed your example and added my deps and src folder, but the `yarn ios` script opens an iPhone with the app, is there something I missed out?

![image](https://github.com/react-native-tvos/react-native-tvos/assets/30415552/c9d6ad63-298e-4e5c-b3ed-50628525662f)

**Comment by douglowder** [comment] 2024-02-15 00:46
@mendoza be sure that you executed `export EXPO_TV=1` before running `npx expo prebuild --clean`. After that the Podfile should be modified to have platform = tvos.

**Comment by mendoza** [comment] 2024-02-15 00:58
That's weird I ran it again (the first time I used the expo_tv part too) and this time the compiling does mention TV, and it worked ... great! LOL

but I got the same errors once I got into the video component, will test tomorrow/later the expo-av component

```sh
iOS Bundled 146ms (node_modules/expo/AppEntry.js)
[AudioToolbox]        MEMixerChannel.cpp:1006  MEMixerChannel::EnableProcessor: failed to open processor type 0x705f6571
[AudioToolbox]        MEMixerChannel.cpp:1006  MEMixerChannel::EnableProcessor: failed to open processor type 0x705f6571
[AudioToolbox]                AQMEIO.cpp:198   timed out after 15.000s (0 0); suspension count=0 (IOSuspensions: )
[AudioToolbox]  MEDeviceStreamClient.cpp:467   AQME Default-InputOutput: client stopping after failed start: <AudioQueueObject@0x108204200; Unknown figplayer; [71894]; play>; running
count now 0
 LOG  Error {"error": {"code": -66681, "domain": "CoreMediaErrorDomain", "localizedDescription": "The operation couldn’t be completed. (CoreMediaErrorDomain error -66681.)", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 2503}

```

**Comment by douglowder** [comment] 2024-02-15 01:23
hmm.... I'm seeing the same error now, following the same steps I did yesterday.

Opening the same stream URL works fine with VLC app, so it doesn't seem to be a problem on the server side.

I'll also try with expo-av.

**Comment by douglowder** [comment] 2024-02-15 01:28
Wow seeing the same thing now on expo-av

**Comment by douglowder** [comment] 2024-02-15 01:32
Tried other stream URLs with the same result. I'm going to update my Xcode to 15.2, and then try on the simulator, and also on a real Apple TV device and see if the same problem occurs.

**Comment by douglowder** [comment] 2024-02-15 02:06
Hmm now the problem no longer reproduces -- the react-native-video app works fine on both device and simulator.

**Comment by douglowder** [comment] 2024-02-15 02:19
And now I created an app with the community CLI, and the problem is back. Reproduces on simulator, but not on a real device. 😭

**Comment by douglowder** [comment] 2024-02-15 03:36
Seeing this intermittently fail on simulator, but succeed on a real device, makes me think this is some weird Apple simulator bug.... such things were seen before in Xcode 12.

**Comment by mendoza** [comment] 2024-02-15 03:55
The original report I had was from a real device, however it was version `0.73.2`, do you think the minor update could have been what it needs?

**Comment by mendoza** [comment] 2024-02-15 19:52
Tonight my team will finish the expo "port" and deploy to TestFlight to check if it approves the team's test, I will report back 🙌🏼

**Comment by douglowder** [comment] 2024-02-15 20:30
I did some more testing today, and a new Expo app using `expo-av` is having the issue on Apple TV simulator, but not on iPhone simulator. So it is not a template issue, nor is it a problem specific to react-native-video.

The problem seems to happen with both debug and release builds. The problem does NOT happen on a real device. So there may be some issue with the Apple TV simulator that we are somehow hitting.

I'll consult with other Expo SDK developers who work on `expo-av` and see if we can figure out what is going on.

**Comment by douglowder** [comment] 2024-02-15 20:44
Seems like there have been similar issues in the past with simulators playing video and audio: https://github.com/expo/expo/issues/21973

**Comment by mendoza** [comment] 2024-02-15 22:00
My team has encountered that same issue of the audio playing and a blank screen! But it worked as expected on real devices. I'm really hoping expo-av saves the video screen on real devices, after all Simulators aren't perfect 🤷🏻‍♂️

**Comment by mendoza** [comment] 2024-02-19 16:01
Hey @douglowder my team just archived the app for TestFlight (The Expo version), and we got an error about the device's capabilities, when we were uploading it to the app store, the team is on it. But I wanted to let you know, just in case it wasn't something we changed, because I don't remember editing it.

![image](https://github.com/react-native-tvos/react-native-tvos/assets/30415552/b00772fa-d71f-4dc1-9559-9f6087c87209)

**Comment by mendoza** [comment] 2024-02-19 16:02
Hey @douglowder my team just archived the app for TestFlight (The Expo version), and we got an error about the device's capabilities, when we were uploading it to the app store, the team is on it. But I wanted to let you know, just in case it wasn't something we changed, because I don't remember editing it.

![image](https://github.com/react-native-tvos/react-native-tvos/assets/30415552/d92173f3-86ee-498f-8086-d4a38cc568d4)

**Comment by mendoza** [comment] 2024-02-19 17:30
It's live and working on test flight! Thanks so much for your support! You really cleared big questions!
At the end, we are using the `expo` template with `expo-av` for the app. Looks like the issue is just simulators 🤷🏼‍♂️.

I joined expo's discord, I will add send any other good/weird things I notice while we are working on the app, we might go for an EAS deployment too so I might have some feedback.

**Comment by douglowder** [comment] 2024-02-20 11:23
This is great to hear! Thank you for the update. 😄

**Comment by Duell10111** [comment] 2024-02-21 23:09
I think I got the same issue after upgrading to the latest RN 0.73 tvOS with Expo.
I created a new expo project and copied my code with dependencies afterwards.
Repository: https://github.com/Duell10111/ReactTube/tree/expo-template-update

I get similar error messages already mentioned here.
The issue is also only seen on the simulator. :/
Error Logs:
<img width="507" alt="image" src="https://github.com/react-native-tvos/react-native-tvos/assets/1345122/f670f611-40fc-4854-bf9e-f62afa4b6c26">
Part 2:
![image](https://github.com/react-native-tvos/react-native-tvos/assets/1345122/cd3200cf-b78c-44c7-96de-f5e53b2735e5)

Therefore the video never starts playing only a single picture of the video is shown.
I tested it on a Apple TV 17.2 simulator.

**Comment by mendoza** [comment] 2024-02-21 23:24
You are using the VLC component? I didn't dig enough in your repo

**Comment by douglowder** [comment] 2024-02-21 23:52
Oddly enough I created a new tvOS 15.2 simulator today, and the video played fine.

**Comment by Duell10111** [comment] 2024-02-22 14:15
> @Duell10111 You are using the VLC component? I didn't dig enough in your repo

The error logs are from using the react-native-video dependency.
You can enable VLC via a feature flag in my repo, but that does not work either. :D

**Comment by douglowder** [comment] 2024-02-23 10:28
@douglowder this definitely seems to be a bug in the tvOS simulator in the latest Xcode. A simulator created with tvOS 15.2 does not show the issue, but a simulator with tvOS 17.x does show the issue. Closing this.

**Closed by douglowder** 2024-02-23 10:28 UTC

**Comment by Duell10111** [comment] 2024-02-23 12:03
Shouldn't this still be an issue with the expo template/RN tvos version as RN tvos 0.72.6-1 worked fine on the new tvOS 17.x simulators?

**Comment by Duell10111** [comment] 2024-02-23 21:12
> @Duell10111 sadly 0.72.6-1 did not work for me on the new simulators.

Hmm weird, in my app using the old version the HLS still works in the new simulators:
https://github.com/Duell10111/ReactTube

**Comment by joshuaben** [comment] 2024-04-24 18:05
Just wanted to chime in here.  I was getting crashes each time I started an video after upgrading to `0.73.6-3`

...with the help of this post:
https://github.com/expo/create-react-native-app/issues/62#issuecomment-2016416850

I am now able to play the video without issue.

I am using:
`"react-native-video": "^6.0.0-beta.8"`
`"react-native": "npm:react-native-tvos@^0.73.6-3"`
