### ISSUE TITLE
A value for the key 'MinimumOSVersion' in bundle AppName.app/Frameworks/hermes.framework is required

### ISSUE THREAD

**Issue by sjors98** [react-native-tvos/react-native-tvos#563] opened 2023-08-24 09:20 UTC
### Description

Hi!

I've stumbled upon an issue where I can't upload my tvOS app to Testflight because of this errror:

```
 [Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Asset validation failed (90360) Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle AppName.app/Frameworks/hermes.framework is required. (ID: 381878aa-3c85-4d96-8fd3-a84d81624912)
[Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Asset validation failed (90208) Invalid Bundle. The bundle AppName.app/Frameworks/hermes.framework does not support the minimum OS Version specified in the Info.plist. (ID: 3bd914fd-6702-45d9-8794-7aa959cc0e2d)
[Application Loader Error Output]: Error uploading '/var/folders/kw/cr8mdyys6bxb5724f_1tgx_c0000gq/T/d1567ec9-e934-44b8-a3d4-0556960b5456.ipa'.
[Application Loader Error Output]: Asset validation failed Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle AppName.app/Frameworks/hermes.framework is required. (ID: 381878aa-3c85-4d96-8fd3-a84d81624912) (90360)
[Application Loader Error Output]: Asset validation failed Invalid Bundle. The bundle AppName.app/Frameworks/hermes.framework does not support the minimum OS Version specified in the Info.plist. (ID: 3bd914fd-6702-45d9-8794-7aa959cc0e2d) (90208)
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
```

I did however manage to find the cause of this. In `project/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/tvos-arm64/hermes.framework/Info.plist` the `MinimumOSVersion` is missing although it is present in `project/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/Info.plist` 

After adding it I can submit my IPA to testflight using Fastlane but I don't know how to permanently fix it. My first thought was a missing tvOS target in a podspec, but I don't think that's the case

I'm using pnpm as my package manager which already caused some problems for me since we are using react-native-tvos in a monorepo alongside another application which uses the regular react-native. But I don't think it should be a problem here :/ 

### React Native Version

0.71.12-0

### Output of `npx react-native info`

```
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 21.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
    Watchman: 2023.08.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/sjorspolman/.rvm/gems/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-30 | AOSP ATD Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.12-0
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- Setup clean RNtvos project
- Submit to Testflight
- Observe error

### Snack, code example, screenshot, or link to a repository

I don't think this is useful here since it occurs on the base template and while submitting to TestFlight.

**Comment by henninghall** [comment] 2023-08-25 07:20
Experience this error too. Could the root cause be that hermes need to target tvos too when adding the MinimumOSVersion? 🤔
https://github.com/facebook/hermes/blob/016c775b6f7b900b1d530fea0af92720d045269c/API/hermes/CMakeLists.txt#L110

**Comment by henninghall** [comment] 2023-08-25 07:20
This error is also discussed here https://github.com/react-native-tvos/react-native-tvos/issues/517

**Comment by henninghall** [comment] 2023-08-25 09:12
Solved it by adding this to our fastlane build
```rb
set_info_plist_value(
  path: "./ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/tvos-arm64/hermes.framework/Info.plist",
  key: "MinimumOSVersion",
  value: "12.4"
)
```

**Comment by douglowder** [comment] 2023-08-25 18:57
I'll get this fixed for the upcoming 0.72 release.

**Comment by douglowder** [comment] 2023-08-25 20:52
The fix is in the Hermes repo for TV: https://github.com/react-native-tvos/hermes/releases/tag/hermes-2023-08-25-RNv0.72.4-e4a5a201e51cc583b148e8d264a2b061e9408988

Updating the `.hermesversion` in this repo to pick up the fix, and will have this in the next 0.72 release candidate.

**Comment by sjors98** [comment] 2023-08-28 09:31
@douglowder thanks for the quick response! However updating the .hermesversion file doesn't seem to work for me. I've cleaned my project (deleted node modules, reinstalled using the patch, deleting Pods/ and Podfile.lock and reinstalling pods), but it never seems to update the 
`./ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/tvos-arm64/hermes.framework/Info.plist` file. 
Also tried uploading it to Testflight anyway, but then I'll get the same error I used to get before.

**Comment by douglowder** [comment] 2023-08-28 16:50
@sjors98 The `.hermesversion` file is not user-facing; it is used in building the Hermes artifacts that are published as part of a release. Sorry for the confusion. I'll reopen this until a release is published with the fix.

**Comment by douglowder** [comment] 2023-08-29 21:04
Fixed in release 0.71.13-1.

**Closed by douglowder** 2023-08-29 21:04 UTC
Labels: bug, in progress

**Comment by sjors98** [comment] 2023-08-31 07:05
Thanks a lot for the quick fix! Works brilliantly :)

**Comment by santiagoPadi** [comment] 2024-08-10 15:50
> Solved it by adding this to our fastlane build
> 
> ```ruby
> set_info_plist_value(
>   path: "./ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/tvos-arm64/hermes.framework/Info.plist",
>   key: "MinimumOSVersion",
>   value: "12.4"
> )
> ```

works! thanks!

**Comment by harooniqbal1993** [comment] 2024-09-03 09:51
I am using v0.74.4, but still same error. Is there any fix found? I am not using Fastlane.
