### ISSUE TITLE
Focus missing issue while navigate from one screen to another screen and back to the previous screen

### ISSUE THREAD

**Issue by sankar9659** [react-native-tvos/react-native-tvos#237] opened 2021-11-17 09:53 UTC
Hi, I'm working in react-native tvos project, In that, I'm facing one issue, that is, for example, I'm on the home page, in that page I m having some of the focusable grid contents, Initially, the focus was set to one of the touchableopacity content of the screen, If I click any one of the content, I redirect to another page (demo page), Then when I press the back button, the screen is navigated to the previous page (home screen), but the focus is gone somewhere, When I click any one of the buttons in remote then only the focus is visible on the screen, But I need to show the focus initially (I need to focus the same grid content, if I click the first content and go to the next page, then when I come back to the same screen the focus must be in the same grid content). How to fix that issue?
I attached the video below,

React native version:
 "react-native": "npm:react-native-tvos@0.64.2-4",

## Steps To Reproduce

1. Tried to set the focus using hasTVPreferredFocus prop, but I need to focus on the exact content, which I focused on previously, Is that possible?

## Expected Results
Need to focus on the exact content (block) when I click on the backbutton

https://user-images.githubusercontent.com/58698022/142177296-b675600f-14a9-4f3e-896d-93b30f0484c8.mp4

**Comment by TrebuhD** [comment] 2021-11-17 17:13
We currently accomplish this by storing the id of the previously focused element inside redux and setting `hasTVPreferredFocus={itemUniqueId === storedItemId}` on the component. This is obviously not ideal as it requires a lot of boilerplate.

There's a discussion [here](https://github.com/react-native-tvos/react-native-tvos/issues/206) to create an API to streamline this.

Also, there's [this project](https://github.com/darji89/react-native-spatial-navigation) that aims to solve this problem, but it may not be production ready (we've tried it and had mixed results).

**Comment by douglowder** [comment] 2021-11-17 18:02
Please provide source for the project shown in the video, and I'll take a look :)

**Comment by nriccar** [comment] 2021-11-18 00:50
I had the same issue and manage to solve it passing the ref component as a prop on navigation and finding it when the onback event is called, but it is a buggy implementation.

It would be awesome to have this out of the box.

Cheers!

**Comment by todorone** [comment] 2021-11-19 10:30
Also experiencing this issue with `react-navigation`'s stack navigator. Pretty bad thing that the focus is flaky when goBack() to the previous screen. It's probably the result of the race condition of setting the focus commands.

**Comment by douglowder** [comment] 2021-11-20 00:07
I think this would only work out of the box if `react-navigation` is modified to actually know about TV focus and automatically implement something like what @TrebuhD suggests (tracking item IDs or refs and restoring focus when navigating back).  At the moment, `react-navigation` doesn't know anything about TV-specific APIs.

**Comment by TrebuhD** [comment] 2021-11-22 15:26
to expand a little, here's one way you could solve this:
- inside your global store (e.g `redux`) you would have a `shouldRefreshFocus` variable as well as one `lastFocusedItemId` for each screen. Update the last focused item ID inside every touchable's `onFocus` event handler.
- using [navigation events](https://reactnavigation.org/docs/navigation-events/#navigationaddlistener), you can hook into `react-navigation`'s `focus` event and dispatch an action to set `shouldRefreshFocus` to `true`.
- in your focusable components, set 
```typescript
hasTVPreferredFocus={shouldRefreshFocus && lastFocusIndex === "buttonUniqueId"}
```

This should return focus to the last focused item in every screen.

There are 2 main problems with this approach:
- Lots of boilerplate required, it would be great if this worked out-of-the-box.
- It relies on the React rendering lifecycle, which means extra renders that could be prevented if this behaviour was handled on the native side.

**Comment by sankar9659** [comment] 2021-11-24 12:16
> We currently accomplish this by storing the id of the previously focused element inside redux and setting `hasTVPreferredFocus={itemUniqueId === storedItemId}` on the component. This is obviously not ideal as it requires a lot of boilerplate.
> 
> There's a discussion [here](https://github.com/react-native-tvos/react-native-tvos/issues/206) to create an API to streamline this.
> 
> Also, there's [this project](https://github.com/darji89/react-native-spatial-navigation) that aims to solve this problem, but it may not be production ready (we've tried it and had mixed results).

I have tried this method. It's working good, But it seems it's a temporary fix and lot of boilerplate codes.

**Comment by wouterds** [comment] 2022-08-01 23:30
I made an example project because I was planning to create a separate bug, but turns out it works fine in a barebone project with TMDB API 🫠. For those interested, repository available [[here](https://github.com/wouterds/react-native-tv-example)].

https://user-images.githubusercontent.com/1210628/182261998-a7720dde-797d-4c62-b0b3-a3158573aec2.mp4

**Comment by altaywtf** [comment] 2022-11-10 14:17
@TrebuhD thanks a lot for the tip. does your solution work both for Android and Apple TV?
I only made it work on the Apple TV. 🤔

**Comment by TrebuhD** [comment] 2022-11-10 17:06
> @TrebuhD thanks a lot for the tip. does your solution work both for Android and Apple TV?
> 
> I only made it work on the Apple TV. 🤔

It should work - I'm using this mainly with Android TV.

**Comment by mansilaad** [comment] 2022-12-06 03:33
+1 same issue

**Comment by yusufyildirim** [comment] 2023-01-03 23:33
Sort of cross-posting what I shared in #398.

This is a react-navigation (actually, react-native-screens) problem and it should be fixed as @douglowder described [here](https://github.com/react-native-tvos/react-native-tvos/issues/237#issuecomment-974550450). I've been trying to avoid exactly doing that but Android's focus system is incredibly unreliable and `react-native-screens` doesn't make it better. So, we have to do this.

I'm working on creating a patch for `react-navigation` (react-native-screens) to fix this problem. Here's how it works **without** my patch:

https://user-images.githubusercontent.com/22980987/210457967-3ff394d8-3e6a-4258-8cd4-36b48eff8f02.mov

Focus gets lost when we go back to the previous page. And here, **with the patch**:

https://user-images.githubusercontent.com/22980987/210457276-e1324d90-a1c2-463b-9187-ba5560503c96.mov

As can be seen, focus gets restored after the transition. This is maybe like ~10 lines of fix and It is working but I haven't tested it in nested stack scenarios etc. I'll keep working.

**Comment by Imgox** [comment] 2023-01-14 18:53
> 

Hello I'm having the same issue, and you seem to have solved it, can you provide more details on how you managed to fix it, thank you

**Comment by Imgox** [comment] 2023-01-14 18:54
> Sort of cross-posting what I shared in #398.
> 
> This is a react-navigation (actually, react-native-screens) problem and it should be fixed as @douglowder described [here](https://github.com/react-native-tvos/react-native-tvos/issues/237#issuecomment-974550450). I've been trying to avoid exactly doing that but Android's focus system is incredibly unreliable and `react-native-screens` doesn't make it better. So, we have to do this.
> 
> I'm working on creating a patch for `react-navigation` (react-native-screens) to fix this problem. Here's how it works **without** my patch:
> 
>  Screen.Recording.2023-01-04.at.00.24.03.mov 
> Focus gets lost when we go back to the previous page. And here, **with the patch**:
> 
>  Screen.Recording.2023-01-04.at.00.04.13.mov 
> As can be seen, focus gets restored after the transition. This is maybe like ~10 lines of fix and It is working but I haven't tested it in nested stack scenarios etc. I'll keep working.

Hello I'm having the same issue, and you seem to have solved it, can you provide more details on how you managed to fix it, thank you

**Comment by Imgox** [comment] 2023-01-14 20:09
> I made an example project because I was planning to create a separate bug, but turns out it works fine in a barebone project with TMDB API 🫠. For those interested, repository available [[here](https://github.com/wouterds/react-native-tv-example)].
> 
>  demo-tv-app.mp4

I've had a look into your repo, and I tried to apply what you have done on the project I'm working on, but with no luck, can you explain to me just the idea behind your solution, and how to apply it.
thank you

**Comment by josefnorlin** [comment] 2023-01-23 14:22
> > I made an example project because I was planning to create a separate bug, but turns out it works fine in a barebone project with TMDB API 🫠. For those interested, repository available [[here](https://github.com/wouterds/react-native-tv-example)].
> > demo-tv-app.mp4
> 
> I've had a look into your repo, and I tried to apply what you have done on the project I'm working on, but with no luck, can you explain to me just the idea behind your solution, and how to apply it. thank you

I second this. I'm guessing Wouter are changing stuff in the react-navigation code which is why it's hard to get it working only from his example repo. @wouterds would it be possible for you to fork react-navigation / react-native-screens so we could all enjoy your progress?

**Comment by josefnorlin** [comment] 2023-01-24 07:06
@yusufyildirim @wouterds 🤩

**Comment by yusufyildirim** [comment] 2023-01-24 10:13
@sankar9659 I reopened the issue because this is still ongoing. Not a tvOS problem maybe but it's beneficial for the community to keep track of the progress here

**Comment by yusufyildirim** [comment] 2023-01-24 18:32
@douglowder Not yet. I've been waiting to take a look into this issue in-depth before creating an issue on their repo. I'm currently focused on TVFocusGuide 'autoFocus' feature. As soon as I get that out of the door I'll start looking into this issue again. 

’TVFocusGuide’ has an important role here because I have a solution in mind that *can* help us fix this problem without requiring a code change on react-navigation side. It'd be more of a workaround but a very simple one 😄

The main gameplan is still fixing the problem on their side by the way, no worries.

**Comment by yusufyildirim** [comment] 2023-01-31 23:00
Hello everyone. I've found some time to look into the problem again. Created an issue on `react-native-screens` repository. Here you can track the progress: https://github.com/software-mansion/react-native-screens/issues/1706.

The problem seems to be Android-specific. Couldn't reproduce it on tvOS, it just works fine there. If you believe that's not true, please provide a very very basic repro.

So, we have a solution for Android, a fairly simple one. Here I created a PR to @douglowder's TVInputDemo repo so you can test it out: https://github.com/douglowder/TVInputDemo/pull/1

Don't know if this is the ideal solution yet. I'll discuss this potential solution with `react-native-screens` team and see how they think. Meanwhile, don't forget to give it a try!

**Comment by matias-sandell** [comment] 2023-09-07 08:43
Ah, I forgot to comment on this. We've been using your fix @yusufyildirim by patching react-native-screens automatically with https://github.com/ds300/patch-package on yarn install and it has worked beautifully for us for about half a year now.

Keeping my fingers crossed that the fix will get merged by react-native-screens! 🤞

**Comment by yusufyildirim** [comment] 2023-09-18 12:40
New update from `react-native-screens` team here: https://github.com/software-mansion/react-native-screens/issues/1706#issuecomment-1723305374. Official fix is on the way.

**Comment by ali-sao** [comment] 2023-11-19 18:25
You are awesome @yusufyildirim , thank you for your contribution.

**Comment by yusufyildirim** [comment] 2024-02-14 15:27
I think it's safe to close this issue. Thanks to all the participants!

**Closed by yusufyildirim** 2024-02-14 15:27 UTC
Labels: discussion, 3rd party library issue
