### ISSUE TITLE
<Text> element is getting focsed

### ISSUE THREAD

**Issue by abhisheklalnediya** [react-native-tvos/react-native-tvos#438] opened 2023-01-08 14:46 UTC
### Description

\<Text\> is getting focused like Touchable elements. Unable to disable or prevent it from getting focused.

 
  
  ```
 <View style={styles.container}>
      <Image source={bgImage} resizeMode="contain" style={styles.backGround} />

      <View focusable={false} hasTVPreferredFocus={false}>
        <Text disabled>Settings</Text>
      </View>

      <TouchableHighlight
        onPress={onPress}
        style={styles.button}
        onBlur={onBlur}
        onFocus={onFocus}
        onPressIn={onBlur}
        underlayColor={colors.color5}>
          <Text style={styles.text}>{title}</Text>
      </TouchableHighlight>
    </View>
```
    

### Version

0.69.6-0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 7.45 GB / 15.19 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-tvos:  0.69.6-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Run the code snippet
2. Press down once to focus on the Text element
3. Press again for focusing the Toucbable
4. Press up to focus back on the text element

**Comment by yusufyildirim** [comment] 2023-01-08 21:12
Duplicate of https://github.com/react-native-tvos/react-native-tvos/issues/389. Fixed in latest 0.69.6-1 release. Could you try with that one?

Here's the changelog
: https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.69.6-1

**Closed** 2023-01-10 09:51 UTC

**Comment by wouterds** [comment] 2023-01-10 10:21
As mentioned above this will be fixed in an upcoming version and it is a duplicate. For now, you could either use the workaround mentioned in #389 or upgrade to the pre-release.

**Comment by abhisheklalnediya** [comment] 2023-01-14 07:46
Yes, the update fixed the problem.
