### ISSUE TITLE
[TVTouchable] Error: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by jhen0409** [react-native-tvos/react-native-tvos#500] opened 2023-05-10 01:40 UTC
### Description

I got the following error with component used TVTouchable on unmount.

`ExceptionsManager.js:158 Error: Unable to find node on an unmounted component.`

Platform: tvOS, Fabric is turned off.

### Version

0.71.7-0rc1

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 103.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.7-0rc1 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I've a minimum example for reproduce this issue, please see the code example below.

The issue will be caused on `setShowFirst(!showFirst)` with unmounting the 3 touchables. It doesn't happen when its number is less than 3.

\* From https://github.com/react-native-tvos/react-native-tvos/pull/498#issuecomment-1541157999.

### Snack, code example, screenshot, or link to a repository

```js
const [showFirst, setShowFirst] = useState(true);
return (
  <>
    {showFirst && (
      <TouchableOpacity onPress={() => setShowFirst(!showFirst)}>
        <Text>First</Text>
      </TouchableOpacity>
    )}
    {!showFirst &&
      [0, 1, 2].map(key => (
        <TouchableOpacity
          key={String(key)}
          onPress={() => setShowFirst(!showFirst)}
        >
          <Text>Key {key}</Text>
        </TouchableOpacity>
      ))}
  </>
);
```

**Comment by douglowder** [comment] 2023-05-10 10:01
This reproduces 100% of the time... investigating.

**Comment by douglowder** [comment] 2023-05-10 18:16
Very interesting. This seems to be an ordering problem between the setState execution and the rerendering of the components.  If I make the following change to your application code, the problem is solved. So this is a good workaround for the issue while we work on a fix for this.

```jsx
const [showFirst, setShowFirst] = useState(true);
return (
  <>
    {showFirst && (
      <TouchableOpacity onPress={() => setShowFirst(!showFirst)}>
        <Text>First</Text>
      </TouchableOpacity>
    )}
    {!showFirst &&
      [0, 1, 2].map(key => (
        <TouchableOpacity
          key={String(key)}
          onPress={() => setTimeout(() => setShowFirst(!showFirst), 1)}
        >
          <Text>Key {key}</Text>
        </TouchableOpacity>
      ))}
  </>
);
```

**Closed** 2023-05-11 00:52 UTC
Labels: bug

**Comment by prasad-r-g** [comment] 2024-08-08 14:52
hi @douglowder  i am facing this issue "Error: Unable to find node on an unmounted component. " while navigating couldn't get much from the stack trace  in version react-native-tvos@0.73.1-3 any workaround and this is not reproducible always but this is happening mostly while navigating..any suggestions pls let me know


app:///TVTouchable.js in _tvEventHandler.enable$argument_1 at line 44:36
app:///TVEventHandler.js in __nativeTVNavigationEventEmitter.addListener$argument_1 at line 36:18
app:///EventEmitter.js in emit at line 115:35
app:///RCTDeviceEventEmitter.js in emit at line 32:4
[native code] in callFunctionReturnFlushedQueue
