### ISSUE TITLE
[AppleTV] TextInput causes crash

### ISSUE THREAD

**Issue by matthewcaminiti** [react-native-tvos/react-native-tvos#833] opened 2024-11-21 19:23 UTC
On the latest version `0.76.2-0` with `expo@^52.0.7` using a `TextInput` will cause a crash with the following error:

`Exception thrown while executing UI block: -[RCTSingleLineTextInputView setOnBlur:]: unrecognized selector sent to instance 0x<some address>`

To validate this, I tested this out in a fresh project created with `create-expo-app ... -e with-tv`. I tried a number of workarounds but I think this this is an issue in the native implementation.

I'll begin to downgrade versions to try to identify where the break occurs, for now I know the TextInput's were fine in `0.74.3-0`

EDIT: TextInputs work in `0.75.3-0` (`expo@^51.0.18`)

**Comment by douglowder** [comment] 2024-11-21 21:45
Thanks for the report... this is probably the new native events in 0.76.2-0.

**Comment by douglowder** [comment] 2024-11-22 20:15
I am not seeing this behavior. Could you please share your `App.tsx` code that reproduces the crash?

**Comment by douglowder** [comment] 2024-11-22 21:34
Aha found the issue. This problem is specific to apps running without Fabric. It occurs because in the non-Fabric implementation, some views (TextInput, ScrollView) do not inherit from the TV-specific `RCTTVVIew` class.

For correct behavior and to avoid other regressions, I've moved the handler properties to `RCTView`. You can apply this patch and rebuild your native code and the problem should be fixed.

PR to fix this is on the way, heads up @yusufyildirim .

```patch
diff --git a/node_modules/react-native/React/Views/RCTTVView.h b/node_modules/react-native/React/Views/RCTTVView.h
index d4290d7..3d73f92 100644
--- a/node_modules/react-native/React/Views/RCTTVView.h
+++ b/node_modules/react-native/React/Views/RCTTVView.h
@@ -57,18 +57,13 @@
 @property (nonatomic, assign) BOOL trapFocusLeft;
 @property (nonatomic, assign) BOOL trapFocusRight;
 
-
-/**
- * Focus
- */
+// These handlers are defined in RCTView
+/*
 @property (nonatomic, copy) RCTBubblingEventBlock onFocus;
 @property (nonatomic, copy) RCTBubblingEventBlock onBlur;
-
-/**
- * TV Press Handlers
- */
 @property (nonatomic, copy) RCTDirectEventBlock onPressIn;
 @property (nonatomic, copy) RCTDirectEventBlock onPressOut;
+ */
 
 - (instancetype)initWithBridge:(RCTBridge *)bridge;
 
diff --git a/node_modules/react-native/React/Views/RCTView.h b/node_modules/react-native/React/Views/RCTView.h
index 8abda6e..3efbf76 100644
--- a/node_modules/react-native/React/Views/RCTView.h
+++ b/node_modules/react-native/React/Views/RCTView.h
@@ -123,6 +123,25 @@ extern const UIAccessibilityTraits SwitchAccessibilityTrait;
 
 @property (nonatomic, assign) RCTCursor cursor;
 
+#if TARGET_OS_TV
+// For Paper, all views on TV might have focus, blur, pressIn, pressOut handlers,
+// so we need to add these properties here and not in RCTTVView,
+// since some views do not inherit from RCTTVView.
+
+/**
+ * Focus
+ */
+@property (nonatomic, copy) RCTBubblingEventBlock onFocus;
+@property (nonatomic, copy) RCTBubblingEventBlock onBlur;
+
+/**
+ * TV Press Handlers
+ */
+@property (nonatomic, copy) RCTDirectEventBlock onPressIn;
+@property (nonatomic, copy) RCTDirectEventBlock onPressOut;
+
+#endif // TARGET_OS_TV
+
 /**
  * (Experimental and unused for Paper) Pointer event handlers.
  */
```

**Closed** 2024-11-22 21:44 UTC
Labels: bug, in progress
