### ISSUE TITLE
Fork update and release process

### ISSUE THREAD

**Issue by miblanchard** [react-native-tvos/react-native-tvos#32] opened 2019-12-13 19:21 UTC
@dlowder-salesforce I'm interested in knowing more about how you keep this project in sync with the upstream RN and maintain the tvOS/CTV related changes on top of that.  We may end up using this in the future for work, and I'd love the ability to help keep this fork up to date with latest!

I really appreciate that this repo exists and keeps pushing forward improvements for the CTV experience!

**Comment by dlowder-salesforce** [comment] 2019-12-13 19:46
Glad to answer this!!! When upstream RN does a major release, I do the following:

- Fetch the upstream repo with all its tags
- Take the latest release tag (e.g. v0.61.2), and create a base branch with those exact commits (e.g. branch-v0.61.2).  Then I make a new branch (e.g. tvos-v0.61.2) to start applying the tvOS-specific changes.
- Start cherry-picking all the tvOS changes from the previous release, in the same order.  Depending on what the core team has done, this can involve a lot of conflict resolution and adjustments and testing.
- Run the automated tests (`scripts/test-tvos.sh`).
- Cut a release tag and publish.

The above process guarantees that each major release of this repo starts with the exact commits in the corresponding release of react-native core.

For minor releases:

- Fetch the upstream repo with tags.
- Look at all the upstream commits between the latest react-native-tvos release and the current core release.
- Cherry-pick all those changes, in order, to the existing release branch (e.g. tvos-v0.61.2), which may have additional commits to fix bugs, etc.
- Run the automated tests.
- Cut a release tag and publish.

So minor releases are based on a previous minor release.

You can see this whole process by having a look at the release notes.  Hope this helps :)

**Comment by miblanchard** [comment] 2019-12-16 21:15
That is very helpful!  Thanks for explaining. Keep up the awesome work and I hope to be able to put that knowledge to good use in the new year!

**Comment by keshavkaul** [comment] 2020-03-29 10:49
@dlowder-salesforce I wanted to try my hand at pulling in react native 0.62.0, but I'm not sure how to go about it. Could you maybe record a screen session detailing your process so the community can help you in this aspect?  Personally I am eager to make use of the latest react devtools that support hooks which is available in 0.62.0

**Comment by dlowder-salesforce** [comment] 2020-03-30 20:09
@keshavkaul I'll be picking up this work some time in April.  I will try to make a recording detailing the process.  It will be the process for major releases that I described (at a very high level) in my comment above from December.

**Comment by dlowder-salesforce** [comment] 2020-04-10 23:38
@keshavkaul I've started a branch for the 0.62 release.  Here is the process I followed to create the branch (you can create your own fork of `react-native-tvos` and try this yourself):

```sh
git remote add upstream https://github.com/facebook/react-native
git fetch --tags upstream
# Move to the 0.62.2 release tag
git checkout v0.62.2
# Create a new base branch for comparing the tvOS changes
git checkout -b branch-v0.62.2
git push --set-upstream origin branch-v0.62.2
# Create the new branch for tvOS patches and releases based on 0.62.2
git checkout -b tvos-v0.62.2
git push --set-upstream origin tvos-v0.62.2
```

Next I'll start cherry-picking changes in order from the existing tvos-v0.61.5 branch and see how it goes.

**Comment by dlowder-salesforce** [comment] 2020-04-11 01:10
[This comparison](https://github.com/react-native-community/react-native-tvos/compare/branch-v0.61.5...tvos-v0.61.5) shows the commits we need to cherry-pick in order, to add the tvOS changes correctly on top of the commits that form RN core 0.62.2.

I've already added the first three.  The only tricky part of the conflict resolution so far was that `Libraries/react-native/react-native-implementation.js` is now the top level `index.js`, so those changes had to be manually added.

The next big issue we are going to hit is that the new Flipper framework, that seems to be needed for RNTester, does not support tvOS.  I'll have to do a little research to figure out how to deal with this.

**Comment by dlowder-salesforce** [comment] 2020-04-12 01:04
I've now merged all the remaining commits from the tvos-v0.61.5 branch, except for the README.md changes, which can just be copied from master.  Now to work on testing and integrating the new Flipper stuff.

**Comment by dlowder-salesforce** [comment] 2020-04-14 17:16
Made progress on getting Flipper to work with react-native-tvos.  Most of the Flipper podspecs don't include tvOS platform support, but the code compiles fine on tvOS regardless.  So I've created a repo to hold modified podspecs, temporarily housed at https://github.com/dlowder-salesforce/RNTVOS-Podspecs .  Adding this as a source in the Podfile for a RN tvOS project solves most of the issues.  I'm gradually fixing the issues in branch https://github.com/react-native-community/react-native-tvos/tree/dlowder/flipper-test-0.62.2 .

**Comment by dlowder-salesforce** [comment] 2020-04-15 01:29
I got the RNTester Podfile to work with the new Flipper podspecs, but there are some header files that still won't allow AppDelegate.mm to compile in RNTester.  So I have temporarily removed the RNTester project define that pulls in Flipper, and now it compiles and runs at least.  Fixed import issues in the react-native JS code.  Now RNTester comes up, but TouchableHighlight rows are not highlighted as they used to be when they come into focus -- the app seems to work fine otherwise.  I'm seeing the same problem with YellowBox rows, so I suspect something changed in TouchableHighlight.

**Comment by dlowder-salesforce** [comment] 2020-04-15 23:02
Fixed some remaining issues with getting the Cocoapods dependencies correct, and fixed the new project template Podfile.  Remaining issue is the dependency on the OpenSSL-Universal pod, which pulls in prebuilt OpenSSL binaries that only work for iOS, not tvOS.  All commits are now in the tvos-v0.62.2 branch.

**Comment by dlowder-salesforce** [comment] 2020-04-21 18:07
Remaining issues with Flipper are now fixed.  Was able to bring up RNTester on the tvOS simulator, and connected it to Flipper desktop.  Now working on import issues in a few JS files, and then will investigate the issue mentioned above where Touchables are not highlighted when focused as they were in 0.61.

**Comment by dlowder-salesforce** [comment] 2020-04-22 01:36
All issues seem to be resolved now.  The touchable highlighting issue is fixed.  RNTester works as expected from the previous releases, and also works with Flipper.  New projects generated from the template also work as expected, and work with Flipper.  Automated tests (`./scripts/tvos-test.sh test`) now pass (after locally changing `package.json` to have the name `react-native` instead of `react-native-tvos`).  Will do some more local testing... expect to cut a release by the end of the week.

**Comment by dlowder-salesforce** [comment] 2020-04-28 21:11
Ok I was a bit optimistic... Thanks to @vdmtrv for making me aware of some issues with `TVFocusGuideView` that needed to be addressed, and providing a reproducible test case.  PR #65 should fix these.  Once that is merged, I will cut the 0.62 release.

**Comment by dlowder-salesforce** [comment] 2020-04-29 23:18
PR #65 is now merged, and I've added a few minor changes to fix flow and eslint errors.  README is now updated.

**Comment by dlowder-salesforce** [comment] 2020-04-30 00:39
Last step before release is to set the version number correctly in a few files, and generate the Android jars and manifest.  Release is now published: https://github.com/react-native-community/react-native-tvos/releases/tag/v0.62.2-0

**Comment by keshavkaul** [comment] 2020-04-30 13:47
@dlowder-salesforce Thank you so much! Much appreciated in this time of uncertainty :)

**Comment by miblanchard** [comment] 2020-05-03 14:42
@dlowder-salesforce  thank you for all your hard work on this repo, and expanding on this issue in such great detail! 

I greatly appreciate your efforts to maintain this and hope to build something great with this!

**Comment by dlowder-salesforce** [comment] 2020-08-20 19:52
0.63 release is now published: https://github.com/react-native-community/react-native-tvos/releases/tag/v0.63.1-0

**Closed** 2021-07-12 22:54 UTC
Labels: Type: Discussion
