### ISSUE TITLE
Discussion: Example Apps

### ISSUE THREAD

**Issue by raytiley** [react-native-tvos/react-native-tvos#113] opened 2020-09-26 02:23 UTC
Sorry if this is inappropriate thing to post an issue for. I noted a few other general discussion type issues so thought it might be worth a shot.

Are there any example apps using `react-native-tvos` since the fork? Everything I find reference to is pretty old. It would be nice if there was a simple video player app written in react-native-tvos that shows some common usage. Some of the nuance around focusing, navigation stacks etc aren't apparent when starting a new project from scratch, and it would be helpful to have a reference.

Thanks for the project!

**Comment by dlowder-salesforce** [comment] 2020-09-26 06:32
Well my favorite (since I wrote it) is still https://github.com/dlowder-salesforce/RNAppleTVTalk .... it's a little dated, but still works with the latest release of this repo.  There is a video example there.

I have a page up where I tried to consolidate this kind of info: https://dlowder-salesforce.github.io/react-native-apple-tv/ .

Hope this helps :)

**Comment by octopicorn** [comment] 2021-01-24 00:04
@dlowder-salesforce Hi Doug! 
I have run into an issue with the latest 0.63 implementation, related to the top navigation.
Essentially, TabBarIOS just has dramatically changed its funcitonality, to the point where it is unusable now.
And the issue is, there doesn't seem to be a clear alternative or "best practices" method in any demo or tutotrial for RN-tvOS to date.

I went to your repo referenced above RNTVAppleTalk, and I can verify that your project faces the same blocker that I have.
You can reproduce this if you like by cloning that repo fresh and just following the setup in the README.

Here are the main issues:
- the selected tab is now white on white, making it unreadable (see screenshot). this is not a huge deal, can just change the colors np.
- the nav bar no longer covers the entire top area of the screen. Instead it now appears as a thin rounded bar which does not touch the edges.
- worse, the bar does not disappear when you swipe down. previously, the tabbar would dismiss as you swipe down into the main content. now, you are "locked" in the tab bar until you press the main selection button on the remote
- when you press main select button on remote to choose to go "in" to a tab, the tab bar remains on screen, covering content in that tab.

There are probably other edge cases that are problematic with TabBarIOS now, but with just these, the component is unusable.

Because the original behavior was so specific to the TV, it's not trivial to reproduce the functionality with a standalone component. I will try to make my own tab bar type component to replace the navigation, but it will likely involve redux or something to give app-wide universal state to keep track of which tab is selected and whether tabbar is shown or hidden.

Do you have any thoughts on this? 

Attaching screenshot of my local clone of the RNAppleTalk demo app running simulator. The focus cannot "Escape" from the tab unless you press the main select button (the button with the mouse pad on it)

<img width="1146" alt="Screen Shot 2021-01-23 at 3 55 54 PM" src="https://user-images.githubusercontent.com/2448666/105617639-ae8dbe80-5d94-11eb-9ee4-4de2ba1fed64.png">

**Comment by octopicorn** [comment] 2021-01-24 00:09
Sorry this comment above is a duplicate of https://github.com/react-native-tvos/react-native-tvos/issues/17
The tabbar issue is being discussed there. Never mind on this thread, thank you.

**Closed** 2021-07-12 22:53 UTC
Labels: Type: Discussion
